### PR TITLE
Pass arguments to underlying connected functions.

### PR DESCRIPTION
**Pull request by soluml**
Currently there's an issue in this project where a developer is unable to pass arguments from the connected class/function to the underlying implementation.

While trying to implement this fix (which involved two line changes in src/index.js), I was unable to build the project due to the age of the dependencies. After updating some of those and adjusting a few things I was able to get it to produce a UMD module again.

### CODE REVIEW

**Comment by soluml** [comment]
@davej  - I realize this is quite an old project, but if you could take a quick look at this PR and get these updates in it'd be much appreciated.

There are other updates to the dependencies that can be made (old Webpack/Mocha/etc.) but I only updated the ones necessary to get the build to run.

**Comment by davej** [comment]
Thanks @soluml looks good. Can you add a test to test the new functionality?

Once this is added then I'm happy to merge and do a release. I'll probably also update some of the other deps too.

**Comment by soluml** [comment]
Sure, I'll look into that. The change was literally passing the arguments along from the connect implementation to the underlying class so they're probably not going to be all that expansive.

**Comment by soluml** [comment]
@davej - Updated the tests. Good thing I did, I missed the functional hook in index. I think this PR should be good to go! Let me know if that's not the case.  Thanks again!

**Comment by davej** [comment]
Awesome! Can you add lib back to `.gitignore` and then `git rm` it. I'd prefer to keep compiled files out of git, makes it easier to read diffs and commits. :)

**Comment by soluml** [comment]
Normally, I 100% agree.

Though with libraries like this, it can be nice to have the actual files specified by npm in the repo. That way, if someone finds a bug and needs a fix they can fork the repo, make the change, and point their package.json at their fork until resolved.

That's what I'm currently doing with my project and removing the lib from the repo would break that for any future builds until changes get published to npm.

I will certainly remove it if you insist, but I just thought I'd point the above out before I do.

**Comment by davej** [comment]
Yeah, makes sense, forking on npm is tough, I use `patch-package` for this. Please remove lib in this case though. I'll try to publish fairly quick.

**Comment by soluml** [comment]
@davej Done!

**Comment by davej** [comment]
Published as js-redux@2.0.0

**Pull request merged**
